server:
  port: '8082'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springboot_rest
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

welcome:
  message: Bienvenido a mi SpringBootApiRestApplication
