server:
  port: '8082'

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springboot_rest
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

welcome:
  message: Bienvenido a mi SpringBootApiRestApplication

---
spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springboot_rest_qa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

welcome:
  message: Bienvenido a mi SpringBootApiRestApplication
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/springboot_rest_prod
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

welcome:
  message: Bienvenido a mi SpringBootApiRestApplication